version: '2'
services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: a123456
    volumes:
      - ./data/mariadb:/var/lib/mysql
