FROM php:5.6.25-fpm-alpine

COPY repositories /etc/apk/

RUN apk add --no-cache --virtual .build-deps $PHPIZE_DEPS

RUN docker-php-ext-enable opcache

RUN pecl install redis-2.2.8 && docker-php-ext-enable redis

# RUN apk add --no-cache openssl-dev\
#     && pecl install mongodb && docker-php-ext-enable mongodb

RUN apk add --no-cache linux-headers
# special patch for alpine linux-kernel have some strange incompatibility
RUN sed -i "s/struct sigaction {/#ifndef __sighandler_t \ntypedef void (*__sighandler_t)(int);\n#endif\nstruct sigaction\n{/g" /usr/include/signal.h
RUN sed -i "s/union {void (*sa_handler)(int)/__sighandler_t sa_handler/g" /usr/include/signal.h
RUN pecl install swoole && docker-php-ext-enable swoole

# RUN pecl install xdebug && docker-php-ext-enable xdebug

RUN apk add --no-cache libmcrypt-dev && docker-php-ext-install mcrypt

RUN docker-php-ext-install mysql mysqli pdo_mysql

RUN apk add --no-cache libpng-dev libjpeg-turbo-dev freetype-dev\
	&& docker-php-ext-configure gd --with-png-dir --with-jpeg-dir --with-freetype-dir\
	&& docker-php-ext-install gd

RUN apk del .build-deps
