FROM php:5.6.25-apache

MAINTAINER haiwei long "haiwei.free@gmail.com"

COPY /sources.list /etc/apt/sources.list

RUN apt-get update && apt-get install -y libpng12-dev libjpeg-dev imagemagick libfreetype6-dev\
    && docker-php-ext-configure gd --with-png-dir --with-jpeg-dir --with-freetype-dir\
    && docker-php-ext-install mysql mysqli mbstring pdo_mysql gd

RUN apt-get install -y libmcrypt-dev\
    && docker-php-ext-install mcrypt

RUN docker-php-ext-enable opcache

RUN pecl install redis-2.2.7
RUN docker-php-ext-enable redis

RUN pecl install swoole && docker-php-ext-enable swoole

RUN a2enmod rewrite ssl socache_shmcb
COPY /apache2.conf /etc/apache2

CMD ["apache2-foreground"]
